version: "3.9"

services:
  api:
    build: .
    container_name: contract-api
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    restart: unless-stopped

  test:
    build: .
    container_name: contract-api-test
    volumes:
      - .:/app
    command: python -m pytest -v
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    restart: "no"

    # restart: unless-stopped
